name: Deploy static content to Pages
on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the runner

    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the Node.js version you want

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project (optional, if you need a build step)
      - name: Build project
        run: npm run build  # Adjust this if you have a specific build script

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages      # The branch that will be used for deployment
          folder: dist          # The folder containing the built project (your 'dist' folder)
          token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions